Lesson 2 homework
RamzanBersanov/testguru pull request #1
Opened 2022-10-22 21:37 UTC by RamzanBersanov

2022-10-23 07:14 UTC, VidgarVii requested changes

2022-10-23 07:14 UTC, VidgarVii commented on README.md
> +Публикация результатов в соцсети
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

Получается сущности это:
Категория, Тест, Вопрос и т.д

2022-10-23 07:14 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
что делает эта настройка? Она точно нужна?

2022-10-23 07:14 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2022-10-23 07:14 UTC, VidgarVii commented on config/version.rb
> +    VERSION = "0.1.0"
"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2022-10-23 07:14 UTC, VidgarVii commented on public/about.html
> +    <h2>Проект второго модуля обучающего курса Ruby on Rails от школы Thinknetica. Подробнее о школе - на сайте <a href="http://www.thinknetica.com/">www.thinknetica.com</a></h2>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-10-23 07:14 UTC, VidgarVii commented on public/about.html
> +<html lang="en" dir="ltr">
не стыковка с языком. Ни же то текст на русском. А код говорит, что английский

плохая идея делать отступы за счёт параграфов. Грубое нарушение семантики

2022-10-23 11:37 UTC, RamzanBersanov commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
какая? которая в 14 строке?

2022-10-23 13:53 UTC, RamzanBersanov commented on public/about.html
> +<html lang="en" dir="ltr">
не понял, где я сделал отступы?

2022-10-23 14:16 UTC, closed without merging

2022-10-25 05:10 UTC, VidgarVii commented on public/about.html
> +<html lang="en" dir="ltr">
это я случайно лишние скопипастил

2022-10-25 05:10 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
да, комментарий всегда пишется над строчкой, на которой надо сделать исправление