На ветке lesson10
RamzanBersanov/testguru pull request #11
Opened 2023-01-04 22:41 UTC by RamzanBersanov

Изменения, которые будут включены в коммит:
	новый файл:    .vscode/settings.json
	новый файл:    app/assets/stylesheets/flash.scss
	новый файл:    app/assets/stylesheets/nav.scss
	изменено:      app/controllers/application_controller.rb
	изменено:      app/controllers/questions_controller.rb
	новый файл:    app/controllers/sessions_controller.rb
	изменено:      app/controllers/test_passages_controller.rb
	новый файл:    app/controllers/users_controller.rb
	новый файл:    app/helpers/sessions_helper.rb
	новый файл:    app/helpers/users_helper.rb
	изменено:      app/models/user.rb
	новый файл:    app/models/user/auth.rb
	изменено:      app/views/layouts/application.html.erb
	новый файл:    app/views/sessions/_form.html.erb
	новый файл:    app/views/sessions/new.html.erb
	новый файл:    app/views/shared/_nav.html.erb
	новый файл:    app/views/users/_form.html.erb
	новый файл:    app/views/users/new.html.erb
	изменено:      config/routes.rb
	новый файл:    db/migrate/20230101154901_add_password_digest_to_users.rb

2023-01-09 07:06 UTC, VidgarVii requested changes

2023-01-09 07:06 UTC, VidgarVii commented on .vscode/settings.json
> +{
файлы настройки редактора кода к проекту не относятся. Не стоит их класть в репозиторий

2023-01-09 07:06 UTC, VidgarVii commented on app/assets/stylesheets/flash.scss
> +  }
No new lina at end of file

2023-01-09 07:06 UTC, VidgarVii commented on app/assets/stylesheets/nav.scss
> +  }
No new lina at end of file

2023-01-09 07:06 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  end
No new lina at end of file

2023-01-09 07:06 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +          redirect_to tests_path
очень сложный код получился. Если в коде есть вложенные if else значит что-то делаешь не так.
Если кук нет то можно использовать оператор ||
`redirect_to cookies[:users_initial_request] || tests_path`
метод delete вернёт то, что удаляешь. По этому удалять можно сразу при редиректе
`redirect_to cookies.delete(:users_initial_request) || tests_path`

2023-01-09 07:06 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +
No new lina at end of file

2023-01-09 13:58 UTC, RamzanBersanov commented on .vscode/settings.json
> +{
я не знаю, как не класть в репозиторий, то что есть в проекте локально

2023-01-10 06:45 UTC, VidgarVii requested changes

2023-01-10 06:45 UTC, VidgarVii commented on .vscode/settings.json
> +{
коммитеть можно только определенные файлы, а не всё сразу

Чтобы папка не попадала в индекс надо её прописать в gitignore

2023-01-10 06:45 UTC, VidgarVii commented on app/assets/stylesheets/flash.scss
> +
No new lina at end of file не были убраны

2023-01-10 06:45 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    end
тест не создаётся

2023-01-13 04:59 UTC, VidgarVii requested changes

2023-01-13 04:59 UTC, VidgarVii commented on app/assets/stylesheets/flash.scss
> +
не исправлено по всему проекту

2023-01-13 04:59 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id)
автор это текущий пользователь. Не стоит передавть author_id через форму

2023-01-13 05:00 UTC, VidgarVii requested changes

2023-01-13 05:00 UTC, VidgarVii commented on app/views/shared/_nav.html.erb
> +    <%= link_to "Выйти из аккаунта", session_path(session), method: :delete %>
с 6 рельсы такой подход больше не работает

2023-03-06 15:42 UTC, merged