На ветке lesson11: devise, разграничения прав пользователей
RamzanBersanov/testguru pull request #12
Opened 2023-03-08 01:15 UTC by RamzanBersanov

2023-03-08 08:30 UTC, VidgarVii requested changes

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +    before_action :find_question, only: %i[index edit new create update destroy show edit]
в руби используют отступ в 2 пробела

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +    def index
по ТЗ ни где не было такого экшена кроме тестов

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +      answer = @question.answers.build(answer_params)
как тут админ увидет ошибки валидации?

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +      @question = @answer.question
не уверен что нужна переменная @question

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +        redirect_to admin_test_question_answer_path(@test, @question, answer)
как будто тут не используется shallow  в роутах

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +
Пора научиться не допускать No new line at end file

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/answers_controller.rb
> +      redirect_to admin_test_question_answers_url
принято передавать объект ресурса на который будет редирект
admin_question_path(@answer.question)

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/questions_controller.rb
> +    def index
не совсем понятно от куда взялись эти индекса. Стоит следовать ТЗ

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/questions_controller.rb
> +      question = @test.questions.build(question_params)
так же админ не увидет ошибки валидаций.
Стоит протестировать свой код

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test.author_id = current_user.id
тут что-то сложное очень
авторство задается через ассоциации - подумай как это сделать

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/application_controller.rb
нельзя забывать про ограничение доступа

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/devise/sessions_controller.rb
> +  prepend_before_action :require_no_authentication, only: [:new, :create]
если метод не переопределяется, то его переписывать не стоит

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/devise/sessions_controller.rb
> +  def custom_welcome
он ни где не используется

2023-03-08 08:30 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-03-10 05:54 UTC, VidgarVii requested changes

2023-03-10 05:54 UTC, VidgarVii commented on Gemfile
> +gem 'rubocop-rails', '~> 2.18'
rubocop стоит вынести в группу development

2023-03-10 05:54 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
обратти внимание как создаются вопросы. https://github.com/RamzanBersanov/testguru/pull/12/files#diff-8c6583b897d2be3e5daa549b7e9764f5d509e700dfa19a289d11446a5fa483fdR26
Тут можно так же с автором. Как я уже писал ранее - используй ассоциации

2023-03-10 05:54 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +      redirect_to admin_tests_url
1 обычно после создания или обновления ресурса принято юзера отправлять на это ресурс
2 Внутри сайта редиректы стоит использовать с помощью относительных ссылок, а не абсолютных

2023-03-10 05:54 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
в ТЗ нет этого контроллера

2023-03-10 05:54 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> -  def start
как теперь стартовать тест?

2023-03-10 05:54 UTC, VidgarVii commented on config/initializers/my_sessions_devise_override.rb
> +Devise::SessionsController.class_eval do
не очевидное решение. И class_eval опасно использовать.
На много чище было бы наследоваться от Devise::SessionsController и изменить экшен create
И в роутах просто указать нужный контроллер для сессии
https://howilearnedrails.wordpress.com/2013/12/27/how-to-override-and-customize-the-devise-controller-in-rails/

2023-03-10 05:54 UTC, VidgarVii commented on config/initializers/my_sessions_devise_override.rb
> +  end
можно весь код не переписывать, а использовать super
```
super
flash[:notice] = ...
```

2023-03-10 13:05 UTC, RamzanBersanov commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
а это разве не ассоциация?

2023-03-10 14:50 UTC, RamzanBersanov commented on config/initializers/my_sessions_devise_override.rb
> +  end
так не получается

2023-03-11 17:35 UTC, merged