Изменения, которые будут включены в коммит: задание 8
RamzanBersanov/testguru pull request #8
Opened 2022-12-04 12:09 UTC by RamzanBersanov

2022-12-05 03:52 UTC, VidgarVii requested changes

2022-12-05 03:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
этот запрос можно сделать во вью.
Вообще кол-во колбеков надо минимизировать, так как это не явное выполнение кода, которое сложно дебажить и которое ни кто не ожидает

2022-12-05 03:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render :show
после успешного сохранения ресурса стоит делать редирект, а не рендер, чтобы ссылка страницы переписалась

2022-12-05 03:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-12-05 03:52 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    if action == 'create'
для определения создается ресурс или редактируется
лучше использовать хелперы `.persisted?` или `.new_record?`

передавай в метод объект вопроса и по его состоянию ориентируйся что происходит (редактирование или создание)

2022-12-05 03:52 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    Time.now.year
в рельсах рекомендуется использовать `Time.current` вместо `Time.now` (`Time.new`) и `Date.current` вместо `Date.today`
`.current` возвращает текущий момент времени с учетом настройки часового пояса в приложении

2022-12-05 03:52 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    "https://github.com/#{author}/#{repo}"
ТЗ: "Для формирования ссылки на GitHub репозиторий: github_url(author, repo)"
этот хелпер формирует строку, а не ссылку (html)

2022-12-05 03:52 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +  <%= link_to 'TestGuru', github_url("RamzanBersanov", "testguru") %><br>
используй `link_to` внутри хэлпера, а здесь просто вызывай его: `<%= github_url('name', 'test_guru') %>`
текст ссылки `TestGuru` можно также передавать третьим параметром в хэлпер
возможно имеет смысл сделать [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments): `<%= github_url(author: 'name', repo: 'test_guru', title: 'TestGuru') %>`

2022-12-05 03:52 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +  <%= link_to 'TestGuru', github_url("RamzanBersanov", "testguru") %><br>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-12-05 03:52 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +  <%= render "layouts/footer" %>
footer это не layout. Скорей partial

2022-12-07 00:30 UTC, RamzanBersanov commented on app/controllers/questions_controller.rb
> +  end
не понял, как отменять создание пути

2022-12-07 18:03 UTC, merged